# conf/config.yaml
mysql:
  localhost: 127.0.0.1
  port: 3306
  user: root
  password: root
  database: aggregate

im:
  appid: 
  key: 
  root:

server:
  port: 8080

sms:
  ak: 
  sk: 
  sign: 
  template_code: 
  count: 300

domain: http://console.xmml.club

